trigger:
- main
variables:
  buildConfiguration: 'Release'
pool: 
  vmimage: ubuntu-latest
steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: "dotnet build $(buildConfiguration)"